# Data Preprocessing Tools

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv("Data.csv")
x = dataset.iloc [: , :-1].values #MATRIX OF FEATURES, AKA THE VARIABLES USED FOR PREDICTION
y = dataset.iloc [: , -1].values #VECTOR OF DEPENDENT VARIABLE, AKA THE VARIABLE TO BE PREDICTED

In [4]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

## Taking care of missing data

In [6]:
#replacing the missing values with the mean of the column:

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #identifies the missing data entry and states the strategy to be used in replacing them
imputer.fit (x[: , 1:3]) #tells the imputer where the missing values are in the data, here it's the numerical values in the first and second columns
x [: , 1:3] = imputer.transform (x [: , 1:3]) #here it actually updates the matrix x with the imputed values


In [7]:
print (x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [8]:
#Here we have to change the countries names to be numerical values but we have to let the model know that the countries are not ordered

#We can use one hot encoding to turn the country column into 3 columns because there are only 3 countries ; 3 categories

#We will also replace the values in the "Purchased" column with zeroes and ones

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#Creating an object of the ColumnTransformer class:
#The 2 transformer arguments will be what kind of transformation we want to apply to the data and on which indexes of the columns, and the second argument is the remainder, which will stay the same.
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x)) #Connecting the transformer to the matrix of features 'x'


In [9]:
print (x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [10]:
#Here we are going to instead encode the dependant variable, AKA purchased, as a binary variable.

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

NameError: name 'X' is not defined

## Feature Scaling

In [12]:
#Feauture scaling MUST be done AFTER splitting the dataset into training and test sets, so that the test set is not used during the scaling of the training set.
